import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar/NavBar'
import Footer from '@/components/footer/Footer'
import { Provider } from 'react-redux'
import { AppStore, setupStore } from '@/store/store'
import { useRef } from 'react'
import StoreProvider from '@/store/StoreProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const store = setupStore();

  // return <Provider store={storeRef.current}>{children}</Provider>
  return (
    <html lang="en">
      {/* <Provider store={storeRef.current}> */}
      <body className={inter.className}>
        <div className="container">
          <NavBar />
          <StoreProvider>
            {children}
          </StoreProvider>
          <Footer />
        </div>
      </body>
      {/* </Provider> */}
    </html>
  )
}
